### ISSUE TITLE
Compilation Problem With SDK Launcher-Windows

### ISSUE THREAD

**Issue by romaingiard** [readium/SDKLauncher-Windows#28]
Hello,

I've got some problem of compilation whith ReadiumSDKWinLauncher solution (branch master) in Visual Studio 2012 (sdk don't compile)
 I tried to replace readium-sdk project with the release 0.5 but it seems that the Launcher needs ressources like Initialisation.h which are not included in the project.

Thank you for the answer.

**Comment by DennisPopovDn** [comment]
@romaingiard, 
to compile readium-sdk project under Windows it requires to have the Platform Toolset (at least): Visual Studio 2013 (v120),  because of variadic templates compiler issue in lower Microsoft toolset versions

Regards

**Comment by rkwright** [comment]
The Windows builds are not in good shape.  To build Windows, you need to use the branch feature/feature_revised_launcher.  This builds and runs, but it has a lots of bugs.  Any additional work on it would be appreciated.

**Comment by danielweck** [comment]
You can also install Visual Studio 2013 Community Edition (free software), and try this feature branch:
https://github.com/readium/readium-sdk/pull/192
(sorry, this is not merged to the develop / master branch yet, there is ongoing work in feature branches)

**Comment by danielweck** [comment]
...and as Ric said, the https://github.com/readium/SDKLauncher-Windows/tree/feature/feature_revised_launcher branch contains a relatively decent launcher application, with known caveats (for example, the readium-shared-js code is still based on an old revision, not the most recent RequireJS refactoring + plugins)

**Comment by romaingiard** [comment]
Hello,

Thank you for yor answers, I'll try with Visual Studio 2013.
Just one last question about Android Launcher is master branch ok ?

Regards,

2015-09-08 9:24 GMT+02:00 Daniel Weck <notifications@github.com>:

**Comment by danielweck** [comment]
@romaingiard the master branch is now synchronized with the latest architectural changes introduced in the develop branch. So although develop has moved forward a little bit since the last develop >> master merge (release tag), master is a good place to build your apps / run your tests. If you are interested in bleeding edge fixes / improvements, use the develop branch :)
